/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __map_meta_data_hpp__
#define __map_meta_data_hpp__

#include <lcm/lcm_coretypes.h>

#include <string>
#include <vector>


class map_meta_data
{
    public:
        std::string map_name;

        int32_t    width;

        int32_t    height;

        float      grid_width;

        int32_t    map_origin[2];

        int32_t    num_loc;

        std::vector< int32_t > locations_type;

        std::vector< float > locations_x;

        std::vector< float > locations_y;

        std::vector< float > locations_th;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "map_meta_data"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int map_meta_data::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int map_meta_data::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int map_meta_data::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t map_meta_data::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* map_meta_data::getTypeName()
{
    return "map_meta_data";
}

int map_meta_data::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    char* map_name_cstr = const_cast<char*>(this->map_name.c_str());
    tlen = __string_encode_array(
        buf, offset + pos, maxlen - pos, &map_name_cstr, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->grid_width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->map_origin[0], 2);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_loc, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_loc > 0) {
        tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->locations_type[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_loc > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->locations_x[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_loc > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->locations_y[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_loc > 0) {
        tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->locations_th[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int map_meta_data::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    int32_t __map_name_len__;
    tlen = __int32_t_decode_array(
        buf, offset + pos, maxlen - pos, &__map_name_len__, 1);
    if(tlen < 0) return tlen; else pos += tlen;
    if(__map_name_len__ > maxlen - pos) return -1;
    this->map_name.assign(
        static_cast<const char*>(buf) + offset + pos, __map_name_len__ - 1);
    pos += __map_name_len__;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->grid_width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->map_origin[0], 2);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_loc, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    if(this->num_loc) {
        this->locations_type.resize(this->num_loc);
        tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->locations_type[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_loc) {
        this->locations_x.resize(this->num_loc);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->locations_x[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_loc) {
        this->locations_y.resize(this->num_loc);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->locations_y[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    if(this->num_loc) {
        this->locations_th.resize(this->num_loc);
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->locations_th[0], this->num_loc);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int map_meta_data::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->map_name.size() + 4 + 1;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 2);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, this->num_loc);
    enc_size += __float_encoded_array_size(NULL, this->num_loc);
    enc_size += __float_encoded_array_size(NULL, this->num_loc);
    enc_size += __float_encoded_array_size(NULL, this->num_loc);
    return enc_size;
}

uint64_t map_meta_data::_computeHash(const __lcm_hash_ptr *)
{
    uint64_t hash = 0x8f050ade79d5052cLL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
